[project]
name = "pylipd"
version = "1.4.0"

[build-system]
requires = [
    "setuptools>=68.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# This section disables PEP 621 auto-discovery of dynamic fields
metadata.dynamic = []
