
##############################
# Auto-generated. Do not Edit
##############################

import re
from pylipd.utils import uniqid
from pylipd.classes.datatable import DataTable
from pylipd.classes.model import Model

class PaleoData:
    """PyLiPD representation of the `PaleoData` concept from the LinkedEarth ontology.

    This class is AUTO-GENERATED by `create_classes.py`; do not edit by hand.
    Use the public getter/setter helpers to manipulate its fields.
    """

    def __init__(self):
        """Instantiate a blank \`PaleoData\` object with a freshly minted identifier.

        All ontology-defined properties are initialised to `None` (for single-valued
        properties) or an empty list (for multi-valued properties).
        """
        self.misc = {}
        self.ontns = "http://linked.earth/ontology#"
        self.ns = "http://linked.earth/lipd"
        self.type = "http://linked.earth/ontology#PaleoData"
        self.id = self.ns + "/" + uniqid("PaleoData.")

    @staticmethod
    def from_data(id, data) -> 'PaleoData':
        """Create a `PaleoData` instance from a JSON-LD data dictionary produced by
        :py:meth:`to_data`.

        Parameters
        ----------
        id : str
            The URI of the node representing this object in the graph.
        data : dict
            Complete JSON-LD graph keyed by node id.

        Returns
        -------
        PaleoData
            A populated object.
        """
        self = PaleoData()
        self.id = id
        mydata = data[id]
        for key in mydata:
            value = mydata[key]
            obj = None
            if key == "type":
                for val in value:
                    self.type = val["@id"]
        
            elif key == "hasMeasurementTable":
                for val in value:
                    if "@id" in val:
                        obj = DataTable.from_data(val["@id"], data)
                    else:
                        obj = val["@value"]
            
                    self.measurementTables.append(obj)
        
            elif key == "hasName":
                for val in value:
                    if "@value" in val:
                        obj = val["@value"]                        
                    self.name = obj
        
            elif key == "modeledBy":
                for val in value:
                    if "@id" in val:
                        obj = Model.from_data(val["@id"], data)
                    else:
                        obj = val["@value"]
            
                    self.modeledBy.append(obj)
            else:
                for val in value:
                    obj = None
                    if "@id" in val:
                        obj = data[val["@id"]]
                    elif "@value" in val:
                        obj = val["@value"]
                    self.set_non_standard_property(key, obj)
            
        return self

    def to_data(self, data={}):
        """Serialise the object to the LiPD JSON-LD graph structure used internally.

        Parameters
        ----------
        data : dict, optional
            Graph dictionary to append the representation into. New dictionaries
            are created on demand.

        Returns
        -------
        dict
            Updated graph dictionary.
        """
        data[self.id] = {}
        data[self.id]["type"] = [
            {
                "@id": self.type,
                "@type": "uri"
            }
        ]

        if len(self.measurementTables):
            data[self.id]["hasMeasurementTable"] = []
        for value_obj in self.measurementTables:
            if type(value_obj) is str:
                obj = {
                    "@value": value_obj,
                    "@type": "literal",
                    "@datatype": "http://www.w3.org/2001/XMLSchema#string"
                }
            else:
                obj = {
                    "@id": value_obj.id,
                    "@type": "uri"
                }
                data = value_obj.to_data(data)
            data[self.id]["hasMeasurementTable"].append(obj)

        if len(self.modeledBy):
            data[self.id]["modeledBy"] = []
        for value_obj in self.modeledBy:
            if type(value_obj) is str:
                obj = {
                    "@value": value_obj,
                    "@type": "literal",
                    "@datatype": "http://www.w3.org/2001/XMLSchema#string"
                }
            else:
                obj = {
                    "@id": value_obj.id,
                    "@type": "uri"
                }
                data = value_obj.to_data(data)
            data[self.id]["modeledBy"].append(obj)

        if self.name:
            value_obj = self.name
            obj = {
                "@value": value_obj,
                "@type": "literal",
                "@datatype": "http://www.w3.org/2001/XMLSchema#string"
            }
            data[self.id]["hasName"] = [obj]
                
        for key in self.misc:
            value = self.misc[key]
            data[self.id][key] = []
            ptype = None
            tp = type(value).__name__
            if tp == "int":
                ptype = "http://www.w3.org/2001/XMLSchema#integer"
            elif tp == "float" or tp == "double":
                ptype = "http://www.w3.org/2001/XMLSchema#float"
            elif tp == "str":
                if re.match(r"\d{4}-\d{2}-\d{2}( |T)\d{2}:\d{2}:\d{2}", value):
                    ptype = "http://www.w3.org/2001/XMLSchema#datetime"   
                elif re.match(r"\d{4}-\d{2}-\d{2}", value):
                    ptype = "http://www.w3.org/2001/XMLSchema#date"
                else:
                    ptype = "http://www.w3.org/2001/XMLSchema#string"
            elif tp == "bool":
                ptype = "http://www.w3.org/2001/XMLSchema#boolean"

            data[self.id][key].append({
                "@value": value,
                "@type": "literal",
                "@datatype": ptype
            })
        
        return data

    def to_json(self):
        """Return a lightweight, user-friendly JSON representation of the object.
        Intended for external consumption (e.g., saving to file or UI rendering).
        """
        data = {
            "@id": self.id
        }

        if len(self.measurementTables):
            data["measurementTable"] = []
        for value_obj in self.measurementTables:
            obj = value_obj.to_json()
            data["measurementTable"].append(obj)

        if len(self.modeledBy):
            data["model"] = []
        for value_obj in self.modeledBy:
            obj = value_obj.to_json()
            data["model"].append(obj)

        if self.name:
            value_obj = self.name
            obj = value_obj
            data["paleoDataName"] = obj

        for key in self.misc:
            value = self.misc[key]
            data[key] = value
                   
        return data

    @staticmethod
    def from_json(data) -> 'PaleoData':
        """Re-instantiate a `PaleoData` from the lightweight JSON produced by
        :py:meth:`to_json`.

        Parameters
        ----------
        data : dict
            JSON representation.

        Returns
        -------
        PaleoData
            Populated instance.
        """
        self = PaleoData()
        for key in data:
            pvalue = data[key]
            if key == "@id":
                self.id = pvalue
            elif key == "measurementTable":
                for value in pvalue:
                    obj = DataTable.from_json(value)
                    self.measurementTables.append(obj)
            elif key == "model":
                for value in pvalue:
                    obj = Model.from_json(value)
                    self.modeledBy.append(obj)
            elif key == "paleoDataName":
                    value = pvalue
                    obj = value
                    self.name = obj
            else:
                self.set_non_standard_property(key, pvalue)
                   
        return self

    def set_non_standard_property(self, key, value):
        """Assign a non-ontology property.

        These *misc* properties are preserved during serialisation but have no
        dedicated first-class attribute on the object.
        """
        if key not in self.misc:
            self.misc[key] = value
    
    def get_non_standard_property(self, key):
        """Retrieve a previously stored non-ontology property.

        Raises
        ------
        KeyError
            If the property is not present.
        """
        return self.misc[key]
                
    def get_all_non_standard_properties(self):
        """Return the entire miscellaneous property dictionary."""
        return self.misc

    def add_non_standard_property(self, key, value):
        """Append *value* to a list-valued miscellaneous property identified by
        *key*. Creates the list when needed.
        """
        if key not in self.misc:
            self.misc[key] = []
        self.misc[key].append(value)
        
    def getMeasurementTables(self) -> list[DataTable]:
        """Get measurementTables list.

        Returns
        -------
        list[DataTable]
            A list of DataTable objects.
        """
        return self.measurementTables

    def setMeasurementTables(self, measurementTables:list[DataTable]):
        """Set the measurementTables list.

        Parameters
        ----------
        measurementTables : list[DataTable]
            The list to assign.
        """
        assert isinstance(measurementTables, list), "Error: measurementTables is not a list"
        assert all(isinstance(x, DataTable) for x in measurementTables), f"Error: '{measurementTables}' is not of type DataTable"
        self.measurementTables = measurementTables

    def addMeasurementTable(self, measurementTables:DataTable):
        """Add a value to the measurementTables list.

        Parameters
        ----------
        measurementTables : DataTable
            The value to append.
        """
        assert isinstance(measurementTables, DataTable), f"Error: '{measurementTables}' is not of type DataTable"
        self.measurementTables.append(measurementTables)
        
    def getModeledBy(self) -> list[Model]:
        """Get modeledBy list.

        Returns
        -------
        list[Model]
            A list of Model objects.
        """
        return self.modeledBy

    def setModeledBy(self, modeledBy:list[Model]):
        """Set the modeledBy list.

        Parameters
        ----------
        modeledBy : list[Model]
            The list to assign.
        """
        assert isinstance(modeledBy, list), "Error: modeledBy is not a list"
        assert all(isinstance(x, Model) for x in modeledBy), f"Error: '{modeledBy}' is not of type Model"
        self.modeledBy = modeledBy

    def addModeledBy(self, modeledBy:Model):
        """Add a value to the modeledBy list.

        Parameters
        ----------
        modeledBy : Model
            The value to append.
        """
        assert isinstance(modeledBy, Model), f"Error: '{modeledBy}' is not of type Model"
        self.modeledBy.append(modeledBy)
        
    def getName(self) -> str:
        """Get name.

        Returns
        -------
        str
            The current value of name.
        """
        return self.name

    def setName(self, name:str):
        """Set name.

        Parameters
        ----------
        name : str
            The value to assign.
        """
        assert isinstance(name, str), f"Error: '{name}' is not of type str"
        self.name = name
    